<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cmake</string>
		<string>CMakeLists.txt</string>
	</array>
	<key>name</key>
	<string>CMake</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\$)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.cmake</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-markup</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.other.cmake</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(include|project)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.special-method.cmake</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.module.cmake</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#argument</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(function|macro)\s*(\()(.*)(\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.special-method.cmake</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(endfunction|endmacro)\s*(\()(.*)(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.special-method.cmake</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.cmake</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(if|endif|else|elseif|foreach|endforeach)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.cmake</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.cmake</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#argument</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\w+)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cmake</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.cmake</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#argument</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>argument</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-markup</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-literal</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>comment</key>
			<string>Comments (extending until the end of the line).</string>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.cmake</string>
		</dict>
		<key>number-literal</key>
		<dict>
			<key>match</key>
			<string>(\d*.)\d+</string>
			<key>name</key>
			<string>constant.numeric.float.cmake</string>
		</dict>
		<key>string-literal</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.cmake</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-markup</string>
				</dict>
			</array>
		</dict>
		<key>variable-markup</key>
		<dict>
			<key>begin</key>
			<string>(\$)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.cmake</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-markup</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.other.cmake</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cmake</string>
	<key>uuid</key>
	<string>1091985b-ddaa-409b-be15-5d8e6e685849</string>
</dict>
</plist>
